name: pharmacy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio:
  pretty_dio_logger:
  connectivity_plus: ^6.1.3
  get:
  flutter_bloc:
  provider:
  get_it:
  freezed:
  freezed_annotation:
  json_serializable:
  json_annotation: ^4.9.0
  flutter_svg:
  flutter_screenutil:
  easy_localization:
  flutter_gen:
  youtube_player_flutter:
  debounce_throttle:
  equatable:
  animated_toggle_switch:
  shimmer:
  persistent_bottom_nav_bar:
  sqflite:
  path:
  intl:
  flutter_phoenix:
  google_sign_in:
  lottie:
  web_socket_channel:
  firebase_core:
  firebase_messaging:
  google_maps_flutter:
  uuid:
  shared_preferences:
  # flutter_local_notifications: ^14.1.5  # Temporarily disabled due to Android compilation issue
  device_preview: 
  share_plus: 
  url_launcher: 
  flutter_native_splash: 
#  geolocator:
#  geocoding:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator:
  build_runner:
  flutter_gen_runner:

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-Regular.ttf


flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - assets/colors/colors.xml
flutter_intl:
  enabled: true
